import { MODULE_NAME } from './constants';

export const GET_QUESTION = `${MODULE_NAME}.GET_QUESTIONS`;
export const GET_QUESTION_SUCCESS = `${MODULE_NAME}.GET_QUESTIONS_SUCCESS`;
export const GET_QUESTION_FAILURE = `${MODULE_NAME}.GET_QUESTIONS_FAILURE`;

export const GET_CATEGORIES = `${MODULE_NAME}.GET_CATEGORIES`;
export const GET_CATEGORIES_SUCCESS = `${MODULE_NAME}.GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_FAILURE = `${MODULE_NAME}.GET_CATEGORIES_FAILURE`;

export const SET_CATEGORY = `${MODULE_NAME}.SET_CATEGORY`;
