import { MODULE_NAME } from './constants';

export const GET_QUESTION = `${MODULE_NAME}.GET_QUESTION`;
export const GET_QUESTION_SUCCESS = `${MODULE_NAME}.GET_QUESTION_SUCCESS`;
export const GET_QUESTION_FAILURE = `${MODULE_NAME}.GET_QUESTION_FAILURE`;

export const GET_CATEGORIES = `${MODULE_NAME}.GET_CATEGORIES`;
export const GET_CATEGORIES_SUCCESS = `${MODULE_NAME}.GET_CATEGORIES_SUCCESS`;
export const GET_CATEGORIES_FAILURE = `${MODULE_NAME}.GET_CATEGORIES_FAILURE`;

export const SET_CATEGORY = `${MODULE_NAME}.SET_CATEGORY`;
export const SET_QUESTION_NR = `${MODULE_NAME}.SET_QUESTION_NR`;

export const TOGGLE_MODAL = `${MODULE_NAME}.TOGGLE_MODAL`;

export const SUBMIT_ANSWER = `${MODULE_NAME}.SUBMIT_ANSWER`;
export const ANSWER_IS_CORRECT = `${MODULE_NAME}.ANSWER_IS_CORRECT`;
export const ANSWER_IS_INCORRECT = `${MODULE_NAME}.ANSWER_IS_INCORRECT`;

export const GAME_OVER = `${MODULE_NAME}.GAME_OVER`;

export const SET_DIFFICULTY = `${MODULE_NAME}.SET_DIFFICULTY`;
